# Generated by Django 2.0.6 on 2018-06-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score1', models.SmallIntegerField(default=0)),
                ('score2', models.SmallIntegerField(default=0)),
                ('gametime', models.DateTimeField(verbose_name='Game Played')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FW', 'Forward')], max_length=3)),
                ('points', models.SmallIntegerField(default=0)),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['-points', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.User')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='api.Player')),
                ('players', models.ManyToManyField(to='api.Player')),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_captain', to='api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SquadLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.SmallIntegerField(default=0)),
                ('limit', models.SmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=18)),
                ('prequarter_finalist', models.BooleanField(default=False)),
                ('quarter_finalist', models.BooleanField(default=False)),
                ('semi_finalist', models.BooleanField(default=False)),
                ('finalist', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Fixture')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='api.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='api.Team'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
