# Generated by Django 2.0.6 on 2018-06-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'verbose_name_plural': 'Fixtures'},
        ),
        migrations.AlterModelOptions(
            name='lineup',
            options={'verbose_name_plural': 'LineUps'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-points', 'position'], 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'verbose_name_plural': 'Squads'},
        ),
        migrations.AlterModelOptions(
            name='squadlimit',
            options={'verbose_name_plural': 'SquadLimits'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
