# Generated by Django 2.0.6 on 2018-06-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180604_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='picture',
            new_name='flag',
        ),
        migrations.AddField(
            model_name='team',
            name='trigram',
            field=models.CharField(default='NAN', max_length=3),
        ),
    ]
