# Generated by Django 2.0.6 on 2018-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180604_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='teams'),
        ),
    ]
