# Generated by Django 2.0.6 on 2018-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180604_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
