# Generated by Django 2.0.6 on 2018-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('squad_created', models.BooleanField(default=False)),
                ('score', models.SmallIntegerField(default=0)),
                ('balance', models.SmallIntegerField(default=100)),
                ('round', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
